### ISSUE TITLE
Inactive "Illustration Page"

### ISSUE THREAD

**Issue by huserben** [theliberators/usergroups#5]
In #2 we added a github Action that will create an up to date version of your illustrations from the Assets/Illustrations folder, similar to:
[https://huserben.github.io/usergroups/](https://huserben.github.io/usergroups/)  

The issue with _my version_ of this is that I just forked your repo and it won't update unless I fetch your latest changes - it would be better if the page would be published for this repo (so it would stay up to date).
The action is running on this repo already and it seems to work fine (creating a new version of the _gh-pages_ branch everytime something changes in _Assets/Illustrations_.

If you want to "expose" this directly you would need to set up your repo settings to expose the page as follows:
- Enable Pages
- Use _gh-pages/root_ as Source to it

![repo settings](https://user-images.githubusercontent.com/5486874/173180673-16b43bd9-f8c8-460b-91a8-170ec6215a7a.png)

That's all that is needed to keep an "always up-to-date" webpage of your illustration (and I could get rid of my fork of the repo :-))

Potentially a link to the illustrations could be added to the readme (every once in a while some people ask about it).

**Comment by christiaanverwijs** [comment]
Excellent idea! I've enabled this feature. What do you think @huserben? Check https://theliberators.github.io/usergroups/

**Comment by huserben** [comment]
Looks good to me :-) So I'll disable "my version" and start using this one ;-)
